name: JS Actions

on: [push]

jobs:
  action:

    runs-on: windows-latest

    steps:
    - run: Write-Host "Hellooooo"
    - uses: actions/checkout@v1

    - name: hello-action
      uses: ./.github/actions/hello-world
      with:
        first-greeting: "Learning lab user"

