name: JS Actions

on: 
 push:
  branches: [main]
 pull_request:
   branches: [main1]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hello-action
      uses: ./.github/actions/hello-world

